# Generated by Django 2.0 on 2018-02-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.png', upload_to='user_pics'),
        ),
    ]
